CURRENCY_LIST = "CRO-USD SHIB-USD ETH-USD HBAR-USD XLM-USD LTC-USD MATIC-USD AVAX-USD XMR-USD ICP-USD ETC-USD RUNE-USD USDC-USD SOL-USD XRP-USD DOT-USD BTC-USD USDT-USD ATOM-USD ADA-USD VET-USD BCH-USD DAI-USD FIL-USD LINK-USD BNB-USD DOGE-USD TRX-USD STX4847-USD UNI7083-USD"
DATASET_PERIOD = "1y"
INTERESTED_DATA_FIELD = "Close"
SELECTED_COINS = ["XLM-USD", "BTC-USD", "ICP-USD", "USDT-USD"]

DATASET_CACHE_NAME = "currency-dataset.csv"

# Dataframe column names
COIN_COLUMN_NAME = "Coin"
CLUSTER_COLUMN_NAME = "Cluster"